### ISSUE TITLE
Run result problem

### ISSUE THREAD

**Issue by guo-tech** [MaxHalford/spotgeo-challenge#1]
Hey, mhalford, thank you very much for sharing. With your help, I have successfully run the program and get the target detection result, but the result score on the training set is only 0.65, plus the post-processing step score is only 0.56, which is very different from the expected result Great, maybe something went wrong there. I would like to ask if your script program named 6_score calls a script program named toolbox, and what is the function of this toolbox script program. Another interesting thing is that I ran a feature extraction program named 4_features on a computer with ubuntu installed and 256G of memory, and found that during the process of point feature extraction of 32,000 frames of images, its memory usage continued to increase, at least Occupies 30G of memory, I don’t know if this is normal

**Comment by MaxHalford** [comment]
Hey @guo-tech.

> I have successfully run the program and get the target detection result, but the result score on the training set is only 0.65, plus the post-processing step score is only 0.56, which is very different from the expected result

That's very weird for the score... I'm pretty sure I commited the best score.

> I would like to ask if your script program named 6_score calls a script program named toolbox, and what is the function of this toolbox script program

Yes, the 6th script imports the `toolbox.py` module, which is located in `scripts`. 

> Another interesting thing is that I ran a feature extraction program named 4_features on a computer with ubuntu installed and 256G of memory, and found that during the process of point feature extraction of 32,000 frames of images, its memory usage continued to increase, at least Occupies 30G of memory, I don’t know if this is normal

I ran all this code on a MacBook Pro with 24G RAM. I'm aware that the feature extraction script consumes a lot of memory. It's possible to rewrite it so that it writes the features to the disk progressively but I didn't bother doing that.

**Comment by guo-tech** [comment]
What is the F1 score of your algorithm on the training set before the post-processing procedure? I want to see if there is a problem.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaxHalford/spotgeo-challenge"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 下午5:27
收件人:&nbsp;"MaxHalford/spotgeo-challenge"<spotgeo-challenge@noreply.github.com&gt;;
抄送:&nbsp;"1604646142"<1604646142@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MaxHalford/spotgeo-challenge] Run result problem (#1)





 
Hey @guo-tech.
  
I have successfully run the program and get the target detection result, but the result score on the training set is only 0.65, plus the post-processing step score is only 0.56, which is very different from the expected result
  
That's very weird for the score... I'm pretty sure I commited the best score.
  
I would like to ask if your script program named 6_score calls a script program named toolbox, and what is the function of this toolbox script program
  
Yes, the 6th script imports the toolbox.py module, which is located in scripts.
  
Another interesting thing is that I ran a feature extraction program named 4_features on a computer with ubuntu installed and 256G of memory, and found that during the process of point feature extraction of 32,000 frames of images, its memory usage continued to increase, at least Occupies 30G of memory, I don’t know if this is normal
  
I ran all this code on a MacBook Pro with 24G RAM. I'm aware that the feature extraction script consumes a lot of memory. It's possible to rewrite it so that it writes the features to the disk progressively but I didn't bother doing that.

**Comment by MaxHalford** [comment]
Around 0.35.

**Comment by guo-tech** [comment]
Aha, this is very distressing. The score running on my computer is around 0.65. Could you send an interesting.pkl file that you use for training? I want to see if there is a problem with my feature extraction. Also, would you like to ask if your scikit_learn library version is 0.23.2?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaxHalford/spotgeo-challenge"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月2日(星期五) 晚上8:39
收件人:&nbsp;"MaxHalford/spotgeo-challenge"<spotgeo-challenge@noreply.github.com&gt;;
抄送:&nbsp;"1604646142"<1604646142@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MaxHalford/spotgeo-challenge] Run result problem (#1)





 
Around 0.35.

**Comment by MaxHalford** [comment]
Sorry but I'm not very inclined to run it. The competition is over and I'm the only person to have opensourced my code. It's left a bitter taste in my mouth. Also running all the scripts takes around 10 hours on my laptop. Actually I was using scikit-learn 0.23.1.

What score do you obtain after post-processing?

**Comment by guo-tech** [comment]
Well, thank you very much for your sharing and patient guidance.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaxHalford/spotgeo-challenge"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月2日(星期五) 晚上9:18
收件人:&nbsp;"MaxHalford/spotgeo-challenge"<spotgeo-challenge@noreply.github.com&gt;;
抄送:&nbsp;"1604646142"<1604646142@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MaxHalford/spotgeo-challenge] Run result problem (#1)





 
Sorry but I'm not very inclined to run it. The competition is over and I'm the only person to have opensourced my code. It's left a bitter taste in my mouth. Also running all the scripts takes around 10 hours on my laptop. Actually I was using scikit-learn 0.23.1.
