### ISSUE TITLE
Runtime probelm

### ISSUE THREAD

**Issue by healthyOddity** [MaxHalford/spotgeo-challenge#2]
Hi Max, i'm a college student very intrerested in your great work on spotGEO challenge.when i got to the 4.features part i found that the runtime of it is unacceptable and i wonder if this pipeline could be on GPU to speed up

**Comment by healthyOddity** [comment]
also this code consume so much memory that after 7 hours' execution, it's out of memory ,makeing me so desperate :(
I'd appreciate it if you can send me the interesting.pkl file for me to countinue.
As a new hand,thank u so much for your help!

**Comment by MaxHalford** [comment]
Sorry but I don't maintain this code. I just wrote it for the challenge. And yes I remember the featurization part was very time consuming.

**Comment by healthyOddity** [comment]
thank U so much

**Comment by healthyOddity** [comment]
May i ask how many pixels are there in your interesting.pkl approximately? mine contains 10GB's data
